# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    assignees:
      - "ralphorama"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "America/New_York"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
    ignore:
      - dependency-name: "dotenv"
    commit-message:
      prefix: "dependabot (npm)"
      prefix-development: "dependabot (npm dev)"
      include: "scope"
