# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "ralphorama"
    schedule:
      interval: "weekly"
      time: "18:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "github actions"
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "ralphorama"
    schedule:
      interval: "weekly"
      time: "18:00"
      timezone: "America/New_York"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # hold back typescript for @typescript-eslint/typescript-estree
      - dependency-name: "typescript"
        versions: ">= 5.6.0"
      # Not sure why dependabot keeps trying to bump stuff by major versions
      # but it's ticking me off!!
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "npm (prod)"
      prefix-development: "npm (dev)"
