repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]s$
        additional_dependencies:
          - "eslint@8.56.0"
          - "@typescript-eslint/eslint-plugin@6.15.0"
          - "@typescript-eslint/parser@6.15.0"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: \.(json|md|mts|sql)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        name: lint dockerfile

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        name: lint docker-compose
        files: (docker-)?compose(\..*)?\.ya?ml$
