# 1) Copy this file from docker-compose.example.yml to docker-compose.yml
# 2) Edit the `environment` section to use your bot's token
#     i.e. `DISCORD_BOT_TOKEN=123456.789.10`
# 3) execute `docker compose up` to start the bot

services:
  linkfix_bot:
    image: ghcr.io/podaboutlist/linkfix-for-discord:latest
    # Use SIGKILL to emulate Ctrl+C (discord.js does not handle SIGTERM)
    stop_signal: SIGKILL
    environment:
      - DISCORD_BOT_TOKEN=your.bot.token.here
      - LOCALE=en
      - LINKFIX_DEBUG=0
      - INSTAGRAM_FIX_URL=ddinstagram.com
      - PIXIV_FIX_URL=phixiv.net
      - REDDIT_FIX_URL=vxreddit.com
      - TIKTOK_FIX_URL=vxtiktok.com
      - TWITTER_FIX_URL=fxtwitter.com
      - YOUTUBE_FIX_URL=youtu.be
