name: Build

on:
  workflow_call:

jobs:
  docker:
    # strategy:
    #   # make sure to adjust the release.yml workflow when adding new platforms
    #   matrix:
    #     os: [linux]
    #     # arm/v7 support currently blocked by https://gitlab.com/qemu-project/qemu/-/issues/1729
    #     # see https://github.com/docker/build-push-action/issues/977
    #     platform: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # QEMU is required for building multi-arch images
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          # NB: make sure to adjust the _build.yml workflow when adding new platforms
          # NB: arm/v7 support currently blocked by https://gitlab.com/qemu-project/qemu/-/issues/1729
          # (see https://github.com/docker/build-push-action/issues/977)
          platforms: "linux/arm64,linux/amd64"
          push: false
          tags: "${{ github.repository }}:${{ github.sha }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
