name: 'Lint and publish to ghcr.io'
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13"
  # NB: "v" prefix is removed
  release:
    types:
      - published

  # publish "latest" tag on pushes to the main branch
  push:
    branches:
      - main
jobs:
  prettier_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies with NPM
        run: npm ci --ignore-scripts

      - name: Lint src/**/*.ts with Prettier
        run: npm run lint

  ghcr_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    # Don't try to build the Docker image unless linting succeeds
    needs: prettier_lint
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
