name: Release

on:
  push:
    branches: ["main"]
    tags: ["**"]

jobs:
  lint:
    uses: "./.github/workflows/callable/lint.yml"

  build:
    uses: "./.github/workflows/callable/build.yml"
    needs: ["lint"]

  publish-to-ghcr:
    needs: ["build"]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
