name: Release

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  lint:
    uses: "./.github/workflows/_lint.yml"

  build:
    uses: "./.github/workflows/_build.yml"

  publish-image:
    name: Publish Docker Image
    needs: ["lint", "build"]
    runs-on: ubuntu-latest
    env:
      # Set CALCULATED_IMAGE_TAG to "latest" or "vX.Y.Z"
      CALCULATED_IMAGE_TAG: "${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}"
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove 'v' From SemVer Tags
        run: |
          export CALCULATED_TAG=$(echo ${{ env.CALCULATED_IMAGE_TAG }} | sed 's/^v//g')
          echo "Calculated image tag is $CALCULATED_TAG"
          echo "CALCULATED_IMAGE_TAG=$CALCULATED_TAG" >> "$GITHUB_ENV"

      - name: Upload Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.CALCULATED_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-github-release:
    name: Publish GitHub Release w/ Changelog
    needs: ["lint", "build"]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Only run when a tag named vX.Y.Z is pushed
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # LinkFix vX.Y.Z
          name: LinkFix ${{ github.ref_name }}
          body: |+
            LinkFix was updated! You can find the latest Docker images on the [packages page](https://github.com/podaboutlist/linkfix-for-discord/pkgs/container/linkfix-for-discord).

            Here's everything that's changed:
          # TODO: Change this to `false` once we're happy with the generation
          draft: true
          # See .github/release for generation parameters
          generate_release_notes: true
